### ISSUE TITLE
espressobin: nonsensical mdio/hwmon temperature values

### ISSUE THREAD

**Issue by sarnold** [globalscaletechnologies/linux#1]
I haven't figured out where yet (as in which commit) but this was working fine back in 4.14.x and got broken somewhere in the 5.x kernel series.  The (non-working) values returned are always ``-75 C``.

Working with the earlier 4.x mainline espressobin dts, up through the latest 4.14 tag:
```
$ uname -a
Linux foobar 4.14.224-aarch64-r0 #1 SMP PREEMPT Tue Mar 9 15:18:35 PST 2021 aarch64 GNU/Linux
$ find /sys/ -name \*temp\*
/sys/devices/platform/soc/soc:internal-regs@d0000000/d0032004.mdio/mdio_bus/d0032004.mdio-mii/d0032004.mdio-mii:01/mdio_bus/!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio/!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio:12/hwmon/hwmon1/temp1_crit
/sys/devices/platform/soc/soc:internal-regs@d0000000/d0032004.mdio/mdio_bus/d0032004.mdio-mii/d0032004.mdio-mii:01/mdio_bus/!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio/!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio:12/hwmon/hwmon1/temp1_input
/sys/devices/platform/soc/soc:internal-regs@d0000000/d0032004.mdio/mdio_bus/d0032004.mdio-mii/d0032004.mdio-mii:01/mdio_bus/!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio/!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio:12/hwmon/hwmon1/temp1_max_alarm
/sys/devices/platform/soc/soc:internal-regs@d0000000/d0032004.mdio/mdio_bus/d0032004.mdio-mii/d0032004.mdio-mii:01/mdio_bus/!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio/!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio:13/hwmon/hwmon2/temp1_crit
/sys/devices/platform/soc/soc:internal-regs@d0000000/d0032004.mdio/mdio_bus/d0032004.mdio-mii/d0032004.mdio-mii:01/mdio_bus/!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio/!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio:13/hwmon/hwmon2/temp1_input
/sys/devices/platform/soc/soc:internal-regs@d0000000/d0032004.mdio/mdio_bus/d0032004.mdio-mii/d0032004.mdio-mii:01/mdio_bus/!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio/!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio:13/hwmon/hwmon2/temp1_max_alarm
/sys/devices/platform/soc/soc:internal-regs@d0000000/d0032004.mdio/mdio_bus/d0032004.mdio-mii/d0032004.mdio-mii:01/mdio_bus/!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio/!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio:11/hwmon/hwmon0/temp1_crit
/sys/devices/platform/soc/soc:internal-regs@d0000000/d0032004.mdio/mdio_bus/d0032004.mdio-mii/d0032004.mdio-mii:01/mdio_bus/!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio/!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio:11/hwmon/hwmon0/temp1_input
/sys/devices/platform/soc/soc:internal-regs@d0000000/d0032004.mdio/mdio_bus/d0032004.mdio-mii/d0032004.mdio-mii:01/mdio_bus/!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio/!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio:11/hwmon/hwmon0/temp1_max_alarm
```

Not working with the same (early) 5.x mainline espressobin dts.
Also not working with (gti) 5.4.53 new dts files or with 5.10.14:

```
$ uname -a
Linux foobar 5.4.53-aarch64-x0 #1 SMP PREEMPT Fri Mar 12 21:33:34 PST 2021 aarch64 GNU/Linux
$ find /sys/ -name \*temp\*
/sys/kernel/debug/tracing/events/thermal/thermal_temperature
/sys/devices/platform/soc/soc:internal-regs@d0000000/d0032004.mdio/mdio_bus/d0032004.mdio-mii/d0032004.mdio-mii:01/mdio_bus/!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio/!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio:12/hwmon/hwmon1/temp1_input
/sys/devices/platform/soc/soc:internal-regs@d0000000/d0032004.mdio/mdio_bus/d0032004.mdio-mii/d0032004.mdio-mii:01/mdio_bus/!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio/!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio:13/hwmon/hwmon2/temp1_input
/sys/devices/platform/soc/soc:internal-regs@d0000000/d0032004.mdio/mdio_bus/d0032004.mdio-mii/d0032004.mdio-mii:01/mdio_bus/!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio/!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio:11/hwmon/hwmon0/temp1_input
```

**Comment by globalscaletechnologies** [comment]
below patch update the 88e6390 temperature sensor reading function, it causes the hwmon get incorrect value. 
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/drivers/net/phy/marvell.c?h=v5.4.53&id=fee2d546414d74052c68e864e3fdbd0e8c692974

the workaround, you maybe can call m88e1510_hwmon_probe() on m88e6390_probe().

**Comment by pali** [comment]
@lunn: FYI

**Comment by pali** [comment]
CC: @elkablo

In `m88e6390_get_temp` function is:
```c
#define MII_MARVELL_MISC_TEST_PAGE    0x06
#define MII_88E6390_TEMP_SENSOR		0x1c
#define MII_88E6390_TEMP_SENSOR_MASK	0xff
...
phy_select_page(phydev, MII_MARVELL_MISC_TEST_PAGE);
for (i = 0; i < MII_88E6390_TEMP_SENSOR_SAMPLES; i++) {
	ret = __phy_read(phydev, MII_88E6390_TEMP_SENSOR);
	sum += ret & MII_88E6390_TEMP_SENSOR_MASK;
}
sum /= MII_88E6390_TEMP_SENSOR_SAMPLES;
*temp = (sum  - 75) * 1000;
```

But this is incorrect for Topaz 88E6341 switch which is on Espressobin.

Temperature sensor is in register 27 (0x1b) at page 6, not in register 0x1c. Temperature in this register is stored in low 8 bits (so mask 0xff is correct), but offset is 25 °C, not 75. Temperature 100 °C is stored as value 0b01111101.

Register 28 (0x1c) at page 6 seems to be unused, so its value is probably zero. Therefore current code `(zero - 75) * 1000` always reports -75 °C as is reported in this bug report.

**Comment by pali** [comment]
@sarnold: Can you provide output of following command from kernel 4.14.x?
```
grep . /sys/class/hwmon/hwmon*/* 2>/dev/null
```

**Comment by pali** [comment]
Note that on Espressobin with mainline 4.19 kernel Topaz switch in dmesg is detected as:
```
[    5.434138] mv88e6085 d0032004.mdio-mii:01: switch 0x3410 detected: Marvell 88E6341, revision 0
[    6.305768] mv88e6085 d0032004.mdio-mii:01 wan (uninitialized): PHY [!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio:11] driver [Marvell 88E6390]
[    6.397763] mv88e6085 d0032004.mdio-mii:01 lan0 (uninitialized): PHY [!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio:12] driver [Marvell 88E6390]
[    6.489764] mv88e6085 d0032004.mdio-mii:01 lan1 (uninitialized): PHY [!soc!internal-regs@d0000000!mdio@32004!switch0@1!mdio:13] driver [Marvell 88E6390]
```

**Comment by sarnold** [comment]
I tried using the kernel doc (with the big fat warning) to sort that out but I suspect it's not so correct.  Anyway, from 4.14.224 I get this:

```
$ grep . /sys/class/hwmon/hwmon*/* 2>/dev/null
/sys/class/hwmon/hwmon0/name:socinternalregsd0000000mdio32004switch01mdio11
/sys/class/hwmon/hwmon0/temp1_crit:100000
/sys/class/hwmon/hwmon0/temp1_input:36000
/sys/class/hwmon/hwmon0/temp1_max_alarm:0
/sys/class/hwmon/hwmon0/uevent:OF_NAME=switch0phy0
/sys/class/hwmon/hwmon0/uevent:OF_FULLNAME=/soc/internal-regs@d0000000/mdio@320 4/switch0@1/mdio/switch0phy0@11
/sys/class/hwmon/hwmon0/uevent:OF_COMPATIBLE_N=0
/sys/class/hwmon/hwmon1/name:socinternalregsd0000000mdio32004switch01mdio12
/sys/class/hwmon/hwmon1/temp1_crit:100000
/sys/class/hwmon/hwmon1/temp1_input:36000
/sys/class/hwmon/hwmon1/temp1_max_alarm:0
/sys/class/hwmon/hwmon1/uevent:OF_NAME=switch0phy1
/sys/class/hwmon/hwmon1/uevent:OF_FULLNAME=/soc/internal-regs@d0000000/mdio@320 4/switch0@1/mdio/switch0phy1@12
/sys/class/hwmon/hwmon1/uevent:OF_COMPATIBLE_N=0
/sys/class/hwmon/hwmon2/name:socinternalregsd0000000mdio32004switch01mdio13
/sys/class/hwmon/hwmon2/temp1_crit:100000
/sys/class/hwmon/hwmon2/temp1_input:36000
/sys/class/hwmon/hwmon2/temp1_max_alarm:0
/sys/class/hwmon/hwmon2/uevent:OF_NAME=switch0phy2
/sys/class/hwmon/hwmon2/uevent:OF_FULLNAME=/soc/internal-regs@d0000000/mdio@320 4/switch0@1/mdio/switch0phy2@13
/sys/class/hwmon/hwmon2/uevent:OF_COMPATIBLE_N=0
```

**Comment by lunn** [comment]
On Fri, Apr 02, 2021 at 04:17:57PM -0700, pali wrote:
> CC: @elkablo
> 
> In m88e6390_get_temp function is:
> 
> #define MII_MARVELL_MISC_TEST_PAGE    0x06
> #define MII_88E6390_TEMP_SENSOR         0x1c
> #define MII_88E6390_TEMP_SENSOR_MASK    0xff
> ...
> phy_select_page(phydev, MII_MARVELL_MISC_TEST_PAGE);
> for (i = 0; i < MII_88E6390_TEMP_SENSOR_SAMPLES; i++) {
>         ret = __phy_read(phydev, MII_88E6390_TEMP_SENSOR);
>         sum += ret & MII_88E6390_TEMP_SENSOR_MASK;
> }
> sum /= MII_88E6390_TEMP_SENSOR_SAMPLES;
> *temp = (sum  - 75) * 1000;
> 
> But this is incorrect for Topaz 88E6341 switch which is on Espressobin.
> 
> Temperature sensor is in register 27 (0x1b) at page 6, not in register 0x1c.
> Temperature in this register is stored in low 8 bits (so mask 0xff is correct),
> but offset is 25 °C, not 75. Temperature 100 °C is stored as value 0b01111101.

That means it is compatible with m88e1510_get_temp().

I assume the 88E6341 suffers from the same problem as the 6390. The
PHY ID values in reg 2 and 3 contain the Marvell OUI, but no device
ID. So mv88e6xxx_mdio_read() looks for this, and inserts the 6390 ID.

So what you need to do is rather insert the family ID. The 88E6341 PHY
would then have a different ID to the 6390 PHY, and you can add a new
PHY to marvell.c for this new PHY ID using the correct temperature
routine.

	Andrew

**Comment by pali** [comment]
@sarnold:
> ```
> /sys/class/hwmon/hwmon0/temp1_crit:100000
> /sys/class/hwmon/hwmon0/temp1_input:36000
> ```

36.000 °C is better than -75.000 °C and looks plausible.

@lunn: Why is mv88e6085 printing into dmesg that `switch 0x3410 detected: Marvell 88E6341` but then choose `driver [Marvell 88E6390]`?

**Comment by lunn** [comment]
On Fri, Apr 02, 2021 at 05:03:20PM -0700, pali wrote:
> @sarnold:
> 
>     /sys/class/hwmon/hwmon0/temp1_crit:100000
>     /sys/class/hwmon/hwmon0/temp1_input:36000
> 
> 36.000 °C is better than -75.000 °C and looks plausible.
> 
> @lunn: Why is mv88e6085 printing into dmesg that switch 0x3410 detected:
> Marvell 88E6341 but then choose driver [Marvell 88E6390]?

I just explained that. Or is github not doing anything with my emails.

  Andrew

**Comment by pali** [comment]
Sorry, my fault, I received it. And now I see it, there is missing mapping between
`MV88E6XXX_FAMILY_*` (read from `chip->info->family`) and `MV88E6XXX_PORT_SWITCH_ID_PROD_*`.

**Comment by pali** [comment]
Quick & dirty patch/hack. Tested on Turris Mox with 88E6141 (not with 88E6341; but both are from FAMILY_6341):
```diff
diff --git a/drivers/net/dsa/mv88e6xxx/chip.c b/drivers/net/dsa/mv88e6xxx/chip.c
index 903d619e08ed..8eb283ede294 100644
--- a/drivers/net/dsa/mv88e6xxx/chip.c
+++ b/drivers/net/dsa/mv88e6xxx/chip.c
@@ -3026,6 +3026,20 @@ static int mv88e6xxx_setup(struct dsa_switch *ds)
 	return err;
 }
 
+static const enum mv88e6xxx_model family_model_table[] = {
+	[MV88E6XXX_FAMILY_6095] = MV88E6095,
+	[MV88E6XXX_FAMILY_6097] = MV88E6097,
+	[MV88E6XXX_FAMILY_6185] = MV88E6185,
+	[MV88E6XXX_FAMILY_6250] = MV88E6250,
+	[MV88E6XXX_FAMILY_6320] = MV88E6320,
+	[MV88E6XXX_FAMILY_6341] = MV88E6341,
+	[MV88E6XXX_FAMILY_6351] = MV88E6351,
+	[MV88E6XXX_FAMILY_6352] = MV88E6352,
+	[MV88E6XXX_FAMILY_6390] = MV88E6390,
+};
+
+static const struct mv88e6xxx_info mv88e6xxx_table[];
+
 static int mv88e6xxx_mdio_read(struct mii_bus *bus, int phy, int reg)
 {
 	struct mv88e6xxx_mdio_bus *mdio_bus = bus->priv;
@@ -3050,13 +3064,9 @@ static int mv88e6xxx_mdio_read(struct mii_bus *bus, int phy, int reg)
 			 * number. But they are not PHYs, so we don't
 			 * want to give them something a PHY driver
 			 * will recognise.
-			 *
-			 * Use the mv88e6390 family model number
-			 * instead, for anything which really could be
-			 * a PHY,
 			 */
 			if (!(val & 0x3f0))
-				val |= MV88E6XXX_PORT_SWITCH_ID_PROD_6390 >> 4;
+				val |= mv88e6xxx_table[family_model_table[chip->info->family]].prod_num >> 4;
 	}
 
 	return err ? err : val;
diff --git a/drivers/net/phy/marvell.c b/drivers/net/phy/marvell.c
index e26a5d663f8a..97c010797d53 100644
--- a/drivers/net/phy/marvell.c
+++ b/drivers/net/phy/marvell.c
@@ -3020,6 +3020,31 @@ static struct phy_driver marvell_drivers[] = {
 		.get_strings = marvell_get_strings,
 		.get_stats = marvell_get_stats,
 	},
+	{
+		.phy_id = MARVELL_PHY_ID_88E6341,
+		.phy_id_mask = MARVELL_PHY_ID_MASK,
+		.name = "Marvell 88E6341",
+		/* PHY_GBIT_FEATURES */
+		.flags = PHY_POLL_CABLE_TEST,
+		.probe = m88e1510_probe,
+		.config_init = marvell_config_init,
+		.config_aneg = m88e6390_config_aneg,
+		.read_status = marvell_read_status,
+		.config_intr = marvell_config_intr,
+		.handle_interrupt = marvell_handle_interrupt,
+		.resume = genphy_resume,
+		.suspend = genphy_suspend,
+		.read_page = marvell_read_page,
+		.write_page = marvell_write_page,
+		.get_sset_count = marvell_get_sset_count,
+		.get_strings = marvell_get_strings,
+		.get_stats = marvell_get_stats,
+		.get_tunable = m88e1540_get_tunable,
+		.set_tunable = m88e1540_set_tunable,
+		.cable_test_start = marvell_vct7_cable_test_start,
+		.cable_test_tdr_start = marvell_vct5_cable_test_tdr_start,
+		.cable_test_get_status = marvell_vct7_cable_test_get_status,
+	},
 	{
 		.phy_id = MARVELL_PHY_ID_88E6390,
 		.phy_id_mask = MARVELL_PHY_ID_MASK,
@@ -3107,6 +3132,7 @@ static struct mdio_device_id __maybe_unused marvell_tbl[] = {
 	{ MARVELL_PHY_ID_88E1540, MARVELL_PHY_ID_MASK },
 	{ MARVELL_PHY_ID_88E1545, MARVELL_PHY_ID_MASK },
 	{ MARVELL_PHY_ID_88E3016, MARVELL_PHY_ID_MASK },
+	{ MARVELL_PHY_ID_88E6341, MARVELL_PHY_ID_MASK },
 	{ MARVELL_PHY_ID_88E6390, MARVELL_PHY_ID_MASK },
 	{ MARVELL_PHY_ID_88E1340S, MARVELL_PHY_ID_MASK },
 	{ MARVELL_PHY_ID_88E1548P, MARVELL_PHY_ID_MASK },
diff --git a/include/linux/marvell_phy.h b/include/linux/marvell_phy.h
index 52b1610eae68..75baacdbc652 100644
--- a/include/linux/marvell_phy.h
+++ b/include/linux/marvell_phy.h
@@ -33,6 +33,7 @@
  * register and returns the switch family ID
  */
 #define MARVELL_PHY_ID_88E6390		0x01410f90
+#define MARVELL_PHY_ID_88E6341		0x01410f41
 
 #define MARVELL_PHY_FAMILY_ID(id)	((id) >> 4)
 
```

**Comment by lunn** [comment]
On Fri, Apr 02, 2021 at 05:58:15PM -0700, pali wrote:
> Quick & dirty patch/hack. Tested on Turris Mox with 88E6141 (not with 88E6341;
> but both are from FAMILY_6341):
> 
> diff --git a/drivers/net/dsa/mv88e6xxx/chip.c b/drivers/net/dsa/mv88e6xxx/chip.c
> index 903d619e08ed..8eb283ede294 100644
> --- a/drivers/net/dsa/mv88e6xxx/chip.c
> +++ b/drivers/net/dsa/mv88e6xxx/chip.c
> @@ -3026,6 +3026,20 @@ static int mv88e6xxx_setup(struct dsa_switch *ds)
>         return err;
>  }
> 
> +static const enum mv88e6xxx_model family_model_table[] = {
> +       [MV88E6XXX_FAMILY_6095] = MV88E6095,
> +       [MV88E6XXX_FAMILY_6097] = MV88E6097,
> +       [MV88E6XXX_FAMILY_6185] = MV88E6185,
> +       [MV88E6XXX_FAMILY_6250] = MV88E6250,
> +       [MV88E6XXX_FAMILY_6320] = MV88E6320,
> +       [MV88E6XXX_FAMILY_6341] = MV88E6341,
> +       [MV88E6XXX_FAMILY_6351] = MV88E6351,
> +       [MV88E6XXX_FAMILY_6352] = MV88E6352,
> +       [MV88E6XXX_FAMILY_6390] = MV88E6390,

You are missing 6393.  This can easily happen, so place add an extra
entry to enum mv88e6xxx_family MV88E6XXX_FAMILY_LAST, and a
BUILD_BUG(ARRAY_SIZE(family_model_table) != MV88E6XXX_FAMILY_LAST).
That should prevent new families being added without this array being
updated, and also means we don't need out of bounds check at runtime.

> +};
> +
> +static const struct mv88e6xxx_info mv88e6xxx_table[];

Forward declarations are not like. Please move the code around to
avoid it.

> +
>  static int mv88e6xxx_mdio_read(struct mii_bus *bus, int phy, int reg)
>  {
>         struct mv88e6xxx_mdio_bus *mdio_bus = bus->priv;
> @@ -3050,13 +3064,9 @@ static int mv88e6xxx_mdio_read(struct mii_bus *bus, int phy, int reg)
>                          * number. But they are not PHYs, so we don't
>                          * want to give them something a PHY driver
>                          * will recognise.
> -                        *
> -                        * Use the mv88e6390 family model number
> -                        * instead, for anything which really could be
> -                        * a PHY,
>                          */

Please update the comment, rather than remove it.

>                         if (!(val & 0x3f0))
> -                               val |= MV88E6XXX_PORT_SWITCH_ID_PROD_6390 >> 4;
> +                               val |= mv88e6xxx_table[family_model_table[chip->info->family]].prod_num >> 4;
>         }
> 
>         return err ? err : val;
> diff --git a/drivers/net/phy/marvell.c b/drivers/net/phy/marvell.c
> index e26a5d663f8a..97c010797d53 100644
> --- a/drivers/net/phy/marvell.c
> +++ b/drivers/net/phy/marvell.c
> @@ -3020,6 +3020,31 @@ static struct phy_driver marvell_drivers[] = {
>                 .get_strings = marvell_get_strings,
>                 .get_stats = marvell_get_stats,
>         },
> +       {
> +               .phy_id = MARVELL_PHY_ID_88E6341,
> +               .phy_id_mask = MARVELL_PHY_ID_MASK,
> +               .name = "Marvell 88E6341",
> +               /* PHY_GBIT_FEATURES */
> +               .flags = PHY_POLL_CABLE_TEST,
> +               .probe = m88e1510_probe,
> +               .config_init = marvell_config_init,
> +               .config_aneg = m88e6390_config_aneg,
> +               .read_status = marvell_read_status,
> +               .config_intr = marvell_config_intr,
> +               .handle_interrupt = marvell_handle_interrupt,
> +               .resume = genphy_resume,
> +               .suspend = genphy_suspend,
> +               .read_page = marvell_read_page,
> +               .write_page = marvell_write_page,
> +               .get_sset_count = marvell_get_sset_count,
> +               .get_strings = marvell_get_strings,
> +               .get_stats = marvell_get_stats,
> +               .get_tunable = m88e1540_get_tunable,
> +               .set_tunable = m88e1540_set_tunable,
> +               .cable_test_start = marvell_vct7_cable_test_start,
> +               .cable_test_tdr_start = marvell_vct5_cable_test_tdr_start,
> +               .cable_test_get_status = marvell_vct7_cable_test_get_status,
> +       },
>         {
>                 .phy_id = MARVELL_PHY_ID_88E6390,
>                 .phy_id_mask = MARVELL_PHY_ID_MASK,
> @@ -3107,6 +3132,7 @@ static struct mdio_device_id __maybe_unused marvell_tbl[] = {
>         { MARVELL_PHY_ID_88E1540, MARVELL_PHY_ID_MASK },
>         { MARVELL_PHY_ID_88E1545, MARVELL_PHY_ID_MASK },
>         { MARVELL_PHY_ID_88E3016, MARVELL_PHY_ID_MASK },
> +       { MARVELL_PHY_ID_88E6341, MARVELL_PHY_ID_MASK },
>         { MARVELL_PHY_ID_88E6390, MARVELL_PHY_ID_MASK },
>         { MARVELL_PHY_ID_88E1340S, MARVELL_PHY_ID_MASK },
>         { MARVELL_PHY_ID_88E1548P, MARVELL_PHY_ID_MASK },
> diff --git a/include/linux/marvell_phy.h b/include/linux/marvell_phy.h
> index 52b1610eae68..75baacdbc652 100644
> --- a/include/linux/marvell_phy.h
> +++ b/include/linux/marvell_phy.h
> @@ -33,6 +33,7 @@
>   * register and returns the switch family ID
>   */
>  #define MARVELL_PHY_ID_88E6390         0x01410f90
> +#define MARVELL_PHY_ID_88E6341         0x01410f41

Please keep these in order.

Otherwise, the code looks O.K. Please submit it to netdev.

       Andrew

**Comment by pali** [comment]
> Otherwise, the code looks O.K. Please submit it to netdev.

It was just quick & dirty hack, I did not thought that is could be O.K :D But fine, I will cleanup it and send to netdev!

**Comment by pali** [comment]
https://lore.kernel.org/netdev/20210412121430.20898-1-pali@kernel.org/T/#u

**Comment by pali** [comment]
@sarnold: Fix is included in 5.12 kernel and also already backported to stable kernel versions: 5.11.16, 5.10.32, 5.4.114, 4.19.189.

**Comment by sarnold** [comment]
Awesome, and thanks!  I got a bit side-tracked working on some new riscv hardware, but I shall update my espressobin kernels shortly.  Congrats on getting your fix mainlined.

**Comment by pali** [comment]
@sarnold: After updating let me know if it is working fine.

**Comment by sarnold** [comment]
Yup, seems to work as expected (3 different v5 boards).  Thanks!

**Comment by pali** [comment]
Perfect, so you can close this issue.
